### ISSUE TITLE
#contentsSelection not working properly for multiple message sends with the same selector

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/MessageSendRecorder#1]
Given any method that includes multiple message sends with the same selector, selecting any of the sends in the tree view will only highlight the first occurrence of the selector in the method source.

Would it be feasible to record the pc of every message send by default to allow an accurate content selection, or would this include a too high overhead? :-)

**Comment by marceltaeumel** [comment]
Fixed.

**Comment by LinqLover** [comment]
Great, thank you! :-)
